const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Mouse,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.googleplay,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{Keyboard: 0},
	{TiledBackground: 0},
	{Solid: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{download: 0},
	{Sprite5: 0},
	{download2: 0},
	{Sprite6: 0},
	{Mouse: 0},
	{Bullet: 0},
	{Food: 0},
	{Exploded: 0},
	{Text: 0},
	{GooglePlay: 0},
	{Browser: 0},
	{PlayerSize: 0},
	{MaxSize: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	download: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	download2: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Food: class extends self.ISpriteInstance {},
	Exploded: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	GooglePlay: class extends self.IInstance {},
	Browser: class extends self.IInstance {}
}